/* The following code was generated by JFlex 1.4.2 on 6/29/08 9:04 AM */

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Copyright (C) 1998-2004  Gerwin Klein <lsf@jflex.de>                    *
 * All rights reserved.                                                    *
 *                                                                         *
 * This program is free software; you can redistribute it and/or modify    *
 * it under the terms of the GNU General Public License. See the file      *
 * COPYRIGHT for more information.                                         *
 *                                                                         *
 * This program is distributed in the hope that it will be useful,         *
 * but WITHOUT ANY WARRANTY; without even the implied warranty of          *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the           *
 * GNU General Public License for more details.                            *
 *                                                                         *
 * You should have received a copy of the GNU General Public License along *
 * with this program; if not, write to the Free Software Foundation, Inc., *
 * 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA                 *
 *                                                                         *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */

/* Java 1.2 language lexer specification */

/* Note that this lexer specification is not tuned for speed.
   It is in fact quite slow on integer and floating point literals, 
   because the input is read twice and the methods used to parse
   the numbers are not very fast. 
   For a production quality application (e.g. a Java compiler) 
   this could be optimized */

package jsyntaxpane.lexers;

import jsyntaxpane.Lexer;
import jsyntaxpane.Token;
import jsyntaxpane.TokenType;
 

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.2
 * on 6/29/08 9:04 AM from the specification file
 * <tt>C:/Ayman/NCB/Java/JSyntaxPane/src/jsyntaxpane/lexers/java.flex</tt>
 */
public final class JavaLexer implements Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int STRING = 2;
  public static final int YYINITIAL = 0;
  public static final int CHARLITERAL = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2, 2
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\7\1\3\1\2\1\0\1\3\1\1\16\7\4\0\1\3\1\71"+
    "\1\24\1\0\1\6\1\71\1\72\1\25\1\65\1\65\1\5\1\74"+
    "\1\65\1\23\1\21\1\4\1\10\1\16\2\15\4\17\2\11\1\65"+
    "\1\65\1\70\1\66\1\67\1\65\1\0\1\14\1\57\1\14\1\60"+
    "\1\22\1\20\2\6\1\61\2\6\1\12\2\6\1\62\3\6\1\64"+
    "\4\6\1\13\2\6\1\65\1\26\1\65\1\71\1\6\1\0\1\27"+
    "\1\30\1\34\1\46\1\37\1\51\1\53\1\43\1\44\1\63\1\41"+
    "\1\36\1\47\1\40\1\35\1\52\1\6\1\33\1\31\1\32\1\45"+
    "\1\54\1\55\1\50\1\42\1\56\1\65\1\73\1\65\1\65\41\7"+
    "\2\0\4\6\4\0\1\6\2\0\1\7\7\0\1\6\4\0\1\6"+
    "\5\0\27\6\1\0\37\6\1\0\u013f\6\31\0\162\6\4\0\14\6"+
    "\16\0\5\6\11\0\1\6\21\0\130\7\5\0\23\7\12\0\1\6"+
    "\13\0\1\6\1\0\3\6\1\0\1\6\1\0\24\6\1\0\54\6"+
    "\1\0\46\6\1\0\5\6\4\0\202\6\1\0\4\7\3\0\105\6"+
    "\1\0\46\6\2\0\2\6\6\0\20\6\41\0\46\6\2\0\1\6"+
    "\7\0\47\6\11\0\21\7\1\0\27\7\1\0\3\7\1\0\1\7"+
    "\1\0\2\7\1\0\1\7\13\0\33\6\5\0\3\6\15\0\4\7"+
    "\14\0\6\7\13\0\32\6\5\0\13\6\16\7\7\0\12\7\4\0"+
    "\2\6\1\7\143\6\1\0\1\6\10\7\1\0\6\7\2\6\2\7"+
    "\1\0\4\7\2\6\12\7\3\6\2\0\1\6\17\0\1\7\1\6"+
    "\1\7\36\6\33\7\2\0\3\6\60\0\46\6\13\7\1\6\u014f\0"+
    "\3\7\66\6\2\0\1\7\1\6\20\7\2\0\1\6\4\7\3\0"+
    "\12\6\2\7\2\0\12\7\21\0\3\7\1\0\10\6\2\0\2\6"+
    "\2\0\26\6\1\0\7\6\1\0\1\6\3\0\4\6\2\0\1\7"+
    "\1\6\7\7\2\0\2\7\2\0\3\7\11\0\1\7\4\0\2\6"+
    "\1\0\3\6\2\7\2\0\12\7\4\6\15\0\3\7\1\0\6\6"+
    "\4\0\2\6\2\0\26\6\1\0\7\6\1\0\2\6\1\0\2\6"+
    "\1\0\2\6\2\0\1\7\1\0\5\7\4\0\2\7\2\0\3\7"+
    "\13\0\4\6\1\0\1\6\7\0\14\7\3\6\14\0\3\7\1\0"+
    "\11\6\1\0\3\6\1\0\26\6\1\0\7\6\1\0\2\6\1\0"+
    "\5\6\2\0\1\7\1\6\10\7\1\0\3\7\1\0\3\7\2\0"+
    "\1\6\17\0\2\6\2\7\2\0\12\7\1\0\1\6\17\0\3\7"+
    "\1\0\10\6\2\0\2\6\2\0\26\6\1\0\7\6\1\0\2\6"+
    "\1\0\5\6\2\0\1\7\1\6\6\7\3\0\2\7\2\0\3\7"+
    "\10\0\2\7\4\0\2\6\1\0\3\6\4\0\12\7\1\0\1\6"+
    "\20\0\1\7\1\6\1\0\6\6\3\0\3\6\1\0\4\6\3\0"+
    "\2\6\1\0\1\6\1\0\2\6\3\0\2\6\3\0\3\6\3\0"+
    "\10\6\1\0\3\6\4\0\5\7\3\0\3\7\1\0\4\7\11\0"+
    "\1\7\17\0\11\7\11\0\1\6\7\0\3\7\1\0\10\6\1\0"+
    "\3\6\1\0\27\6\1\0\12\6\1\0\5\6\4\0\7\7\1\0"+
    "\3\7\1\0\4\7\7\0\2\7\11\0\2\6\4\0\12\7\22\0"+
    "\2\7\1\0\10\6\1\0\3\6\1\0\27\6\1\0\12\6\1\0"+
    "\5\6\2\0\1\7\1\6\7\7\1\0\3\7\1\0\4\7\7\0"+
    "\2\7\7\0\1\6\1\0\2\6\4\0\12\7\22\0\2\7\1\0"+
    "\10\6\1\0\3\6\1\0\27\6\1\0\20\6\4\0\6\7\2\0"+
    "\3\7\1\0\4\7\11\0\1\7\10\0\2\6\4\0\12\7\22\0"+
    "\2\7\1\0\22\6\3\0\30\6\1\0\11\6\1\0\1\6\2\0"+
    "\7\6\3\0\1\7\4\0\6\7\1\0\1\7\1\0\10\7\22\0"+
    "\2\7\15\0\60\6\1\7\2\6\7\7\4\0\10\6\10\7\1\0"+
    "\12\7\47\0\2\6\1\0\1\6\2\0\2\6\1\0\1\6\2\0"+
    "\1\6\6\0\4\6\1\0\7\6\1\0\3\6\1\0\1\6\1\0"+
    "\1\6\2\0\2\6\1\0\4\6\1\7\2\6\6\7\1\0\2\7"+
    "\1\6\2\0\5\6\1\0\1\6\1\0\6\7\2\0\12\7\2\0"+
    "\2\6\42\0\1\6\27\0\2\7\6\0\12\7\13\0\1\7\1\0"+
    "\1\7\1\0\1\7\4\0\2\7\10\6\1\0\42\6\6\0\24\7"+
    "\1\0\2\7\4\6\4\0\10\7\1\0\44\7\11\0\1\7\71\0"+
    "\42\6\1\0\5\6\1\0\2\6\1\0\7\7\3\0\4\7\6\0"+
    "\12\7\6\0\6\6\4\7\106\0\46\6\12\0\51\6\7\0\132\6"+
    "\5\0\104\6\5\0\122\6\6\0\7\6\1\0\77\6\1\0\1\6"+
    "\1\0\4\6\2\0\7\6\1\0\1\6\1\0\4\6\2\0\47\6"+
    "\1\0\1\6\1\0\4\6\2\0\37\6\1\0\1\6\1\0\4\6"+
    "\2\0\7\6\1\0\1\6\1\0\4\6\2\0\7\6\1\0\7\6"+
    "\1\0\27\6\1\0\37\6\1\0\1\6\1\0\4\6\2\0\7\6"+
    "\1\0\47\6\1\0\23\6\16\0\11\7\56\0\125\6\14\0\u026c\6"+
    "\2\0\10\6\12\0\32\6\5\0\113\6\3\0\3\6\17\0\15\6"+
    "\1\0\4\6\3\7\13\0\22\6\3\7\13\0\22\6\2\7\14\0"+
    "\15\6\1\0\3\6\1\0\2\7\14\0\64\6\40\7\3\0\1\6"+
    "\3\0\2\6\1\7\2\0\12\7\41\0\3\7\2\0\12\7\6\0"+
    "\130\6\10\0\51\6\1\7\126\0\35\6\3\0\14\7\4\0\14\7"+
    "\12\0\12\7\36\6\2\0\5\6\u038b\0\154\6\224\0\234\6\4\0"+
    "\132\6\6\0\26\6\2\0\6\6\2\0\46\6\2\0\6\6\2\0"+
    "\10\6\1\0\1\6\1\0\1\6\1\0\1\6\1\0\37\6\2\0"+
    "\65\6\1\0\7\6\1\0\1\6\3\0\3\6\1\0\7\6\3\0"+
    "\4\6\2\0\6\6\4\0\15\6\5\0\3\6\1\0\7\6\17\0"+
    "\4\7\32\0\5\7\20\0\2\6\23\0\1\6\13\0\4\7\6\0"+
    "\6\7\1\0\1\6\15\0\1\6\40\0\22\6\36\0\15\7\4\0"+
    "\1\7\3\0\6\7\27\0\1\6\4\0\1\6\2\0\12\6\1\0"+
    "\1\6\3\0\5\6\6\0\1\6\1\0\1\6\1\0\1\6\1\0"+
    "\4\6\1\0\3\6\1\0\7\6\3\0\3\6\5\0\5\6\26\0"+
    "\44\6\u0e81\0\3\6\31\0\11\6\6\7\1\0\5\6\2\0\5\6"+
    "\4\0\126\6\2\0\2\7\2\0\3\6\1\0\137\6\5\0\50\6"+
    "\4\0\136\6\21\0\30\6\70\0\20\6\u0200\0\u19b6\6\112\0\u51a6\6"+
    "\132\0\u048d\6\u0773\0\u2ba4\6\u215c\0\u012e\6\2\0\73\6\225\0\7\6"+
    "\14\0\5\6\5\0\1\6\1\7\12\6\1\0\15\6\1\0\5\6"+
    "\1\0\1\6\1\0\2\6\1\0\2\6\1\0\154\6\41\0\u016b\6"+
    "\22\0\100\6\2\0\66\6\50\0\15\6\3\0\20\7\20\0\4\7"+
    "\17\0\2\6\30\0\3\6\31\0\1\6\6\0\5\6\1\0\207\6"+
    "\2\0\1\7\4\0\1\6\13\0\12\7\7\0\32\6\4\0\1\6"+
    "\1\0\32\6\12\0\132\6\3\0\6\6\2\0\6\6\2\0\6\6"+
    "\2\0\3\6\3\0\2\6\3\0\2\6\22\0\3\7\4\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\3\1\2\2\1\3\2\4\1\3\2\2\1\5"+
    "\1\6\25\3\6\2\1\7\2\10\1\11\1\1\1\7"+
    "\1\1\1\12\1\0\3\4\1\0\3\4\1\0\32\3"+
    "\2\13\22\3\1\2\1\14\2\7\2\12\1\0\4\4"+
    "\1\0\30\3\1\13\24\3\1\7\2\4\31\3\1\15"+
    "\4\3\2\4\6\3\1\13\7\3\1\13\5\3\2\4"+
    "\14\3\2\4\7\3\2\4\3\3\2\4\2\3\2\4"+
    "\1\0\1\4\1\0\1\4\1\0\1\4\1\0\1\4"+
    "\1\0\1\4\1\0\1\4\1\0\1\4\1\0\5\4";

  private static int [] zzUnpackAction() {
    int [] result = new int[272];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\75\0\172\0\267\0\364\0\u0131\0\u016e\0\u01ab"+
    "\0\u01e8\0\u0225\0\u0262\0\u029f\0\u02dc\0\u0319\0\267\0\267"+
    "\0\u0356\0\u0393\0\u03d0\0\u040d\0\u044a\0\u0487\0\u04c4\0\u0501"+
    "\0\u053e\0\u057b\0\u05b8\0\u05f5\0\u0632\0\u066f\0\u06ac\0\u06e9"+
    "\0\u0726\0\u0763\0\u07a0\0\u07dd\0\u081a\0\267\0\u0857\0\u0894"+
    "\0\u08d1\0\u090e\0\u094b\0\u0988\0\u09c5\0\267\0\267\0\u0a02"+
    "\0\u0a3f\0\u0a7c\0\u0ab9\0\u0af6\0\u0b33\0\u0b70\0\267\0\u0bad"+
    "\0\u0bea\0\u0c27\0\u0c64\0\u0ca1\0\u0cde\0\u0d1b\0\u0d58\0\u0d95"+
    "\0\u0dd2\0\u0e0f\0\u0e4c\0\u0e89\0\u0ec6\0\u0f03\0\u0f40\0\u0f7d"+
    "\0\u0fba\0\u0ff7\0\u1034\0\u1071\0\u10ae\0\u10eb\0\u1128\0\u1165"+
    "\0\u11a2\0\u11df\0\u121c\0\u1259\0\u1296\0\u12d3\0\u01e8\0\u1310"+
    "\0\u134d\0\u138a\0\u13c7\0\u1404\0\u1441\0\u147e\0\u14bb\0\u14f8"+
    "\0\u1535\0\u1572\0\u15af\0\u15ec\0\u1629\0\u1666\0\u16a3\0\u16e0"+
    "\0\u171d\0\u175a\0\u1797\0\267\0\u17d4\0\u1811\0\u184e\0\267"+
    "\0\u188b\0\u18c8\0\u1905\0\u1942\0\u197f\0\u19bc\0\u19f9\0\u1a36"+
    "\0\u1a73\0\u1ab0\0\u1aed\0\u1b2a\0\u1b67\0\u1ba4\0\u1be1\0\u1c1e"+
    "\0\u1c5b\0\u1c98\0\u1cd5\0\u1d12\0\u1d4f\0\u1d8c\0\u1dc9\0\u1e06"+
    "\0\u1e43\0\u1e80\0\u1ebd\0\u1efa\0\u1f37\0\u1f74\0\u1fb1\0\u1fee"+
    "\0\u202b\0\u2068\0\u20a5\0\u20e2\0\u211f\0\u215c\0\u2199\0\u21d6"+
    "\0\u2213\0\u2250\0\u228d\0\u22ca\0\u2307\0\u2344\0\u2381\0\u23be"+
    "\0\u23fb\0\u2438\0\u2475\0\267\0\u24b2\0\u24ef\0\u252c\0\u2569"+
    "\0\u25a6\0\u25e3\0\u2620\0\u265d\0\u269a\0\u26d7\0\u2714\0\u2751"+
    "\0\u278e\0\u27cb\0\u2808\0\u2845\0\u2882\0\u28bf\0\u28fc\0\u2939"+
    "\0\u2976\0\u29b3\0\u29f0\0\u2a2d\0\u2a6a\0\u2aa7\0\u2ae4\0\u01e8"+
    "\0\u2b21\0\u2b5e\0\u2b9b\0\u2bd8\0\u2c15\0\u2c52\0\u2c8f\0\u2ccc"+
    "\0\u2d09\0\u2d46\0\u2d83\0\u2dc0\0\u1d12\0\u2dfd\0\u2e3a\0\u2e77"+
    "\0\u2eb4\0\u2ef1\0\u2f2e\0\u2f6b\0\u2fa8\0\u2fe5\0\u3022\0\u305f"+
    "\0\u309c\0\u30d9\0\u3116\0\u3153\0\u3190\0\u31cd\0\u320a\0\u3247"+
    "\0\u3284\0\u32c1\0\u32fe\0\u333b\0\u3378\0\u33b5\0\u33f2\0\u342f"+
    "\0\u346c\0\u34a9\0\u34e6\0\u3523\0\u3560\0\u359d\0\u35da\0\u3617"+
    "\0\u3654\0\u3691\0\u36ce\0\u370b\0\u3748\0\u3785\0\u37c2\0\u37ff"+
    "\0\u383c\0\u3879\0\u38b6\0\u38f3\0\u3930\0\u396d\0\u39aa\0\u39e7"+
    "\0\u3a24\0\u3a61\0\u3a9e\0\u3adb\0\u3b18\0\u3b55\0\u3b92\0\u3bcf"+
    "\0\u3c0c\0\u3c49\0\u3c86\0\u3cc3\0\u3d00\0\u3d3d\0\u3d7a\0\u3db7";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[272];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\1\5\1\4\1\6\1\7\1\10\1\11\1\4"+
    "\1\12\1\13\3\11\3\13\1\14\1\15\1\11\1\16"+
    "\1\17\1\20\1\4\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\1\11\1\27\1\30\1\31\3\11\1\32\1\11"+
    "\1\33\2\11\1\34\1\35\1\36\1\37\1\40\1\11"+
    "\1\41\1\42\1\43\1\44\1\11\1\45\1\46\1\10"+
    "\1\47\1\50\1\10\1\51\1\52\1\53\1\54\1\55"+
    "\1\56\21\54\1\57\1\54\1\60\46\54\1\61\1\55"+
    "\1\56\22\61\1\57\1\62\46\61\77\0\1\4\75\0"+
    "\1\6\75\0\1\63\1\64\60\0\1\46\74\0\1\46"+
    "\14\0\13\11\1\0\1\11\4\0\36\11\20\0\1\65"+
    "\1\66\1\67\1\70\1\0\1\71\1\72\1\71\1\67"+
    "\1\73\1\74\13\0\1\67\1\74\6\0\1\67\1\0"+
    "\1\70\1\67\6\0\1\67\24\0\2\13\1\67\2\0"+
    "\3\13\1\67\1\73\1\74\13\0\1\67\1\74\6\0"+
    "\1\67\2\0\1\67\6\0\1\67\22\0\13\11\1\0"+
    "\1\11\4\0\7\11\1\75\26\11\20\0\2\73\3\0"+
    "\3\73\100\0\1\46\42\0\1\46\14\0\13\11\1\0"+
    "\1\11\4\0\1\11\1\76\34\11\16\0\13\11\1\0"+
    "\1\11\4\0\4\11\1\77\1\11\1\100\4\11\1\101"+
    "\22\11\16\0\13\11\1\0\1\11\4\0\3\11\1\102"+
    "\7\11\1\103\1\104\1\11\1\105\7\11\1\106\7\11"+
    "\16\0\13\11\1\0\1\11\4\0\4\11\1\107\7\11"+
    "\1\110\21\11\16\0\13\11\1\0\1\11\4\0\10\11"+
    "\1\111\25\11\16\0\13\11\1\0\1\11\4\0\1\112"+
    "\5\11\1\113\1\114\4\11\1\115\21\11\16\0\13\11"+
    "\1\0\1\11\4\0\6\11\1\116\27\11\16\0\13\11"+
    "\1\0\1\11\4\0\7\11\1\117\1\11\1\120\7\11"+
    "\1\121\14\11\16\0\13\11\1\0\1\11\4\0\1\122"+
    "\7\11\1\123\5\11\1\124\17\11\16\0\13\11\1\0"+
    "\1\11\4\0\11\11\1\125\6\11\1\126\1\11\1\127"+
    "\13\11\16\0\13\11\1\0\1\11\4\0\6\11\1\130"+
    "\1\11\1\131\25\11\16\0\13\11\1\0\1\11\4\0"+
    "\1\132\5\11\1\133\1\134\5\11\1\135\20\11\16\0"+
    "\13\11\1\0\1\11\4\0\1\136\3\11\1\137\11\11"+
    "\1\140\17\11\16\0\13\11\1\0\1\11\4\0\6\11"+
    "\1\141\27\11\16\0\13\11\1\0\1\11\4\0\6\11"+
    "\1\142\27\11\16\0\13\11\1\0\1\11\4\0\14\11"+
    "\1\143\21\11\16\0\13\11\1\0\1\11\4\0\6\11"+
    "\1\144\4\11\1\145\22\11\16\0\13\11\1\0\1\11"+
    "\4\0\6\11\1\146\27\11\16\0\13\11\1\0\1\11"+
    "\4\0\11\11\1\147\24\11\16\0\13\11\1\0\1\11"+
    "\4\0\1\11\1\150\34\11\16\0\13\11\1\0\1\11"+
    "\4\0\3\11\1\151\10\11\1\152\21\11\76\0\1\46"+
    "\1\153\73\0\1\46\1\0\1\10\72\0\1\46\3\0"+
    "\1\46\70\0\1\46\4\0\1\46\67\0\1\46\5\0"+
    "\1\46\1\54\2\0\21\54\1\0\1\54\1\0\46\54"+
    "\2\0\1\56\72\0\2\154\1\0\5\154\1\155\4\154"+
    "\2\155\1\156\55\154\1\61\2\0\22\61\2\0\46\61"+
    "\2\154\1\0\72\154\1\63\1\157\1\160\72\63\5\64"+
    "\1\161\67\64\10\0\1\65\1\66\1\67\2\0\1\71"+
    "\1\72\1\71\1\67\1\73\1\74\13\0\1\67\1\74"+
    "\6\0\1\67\2\0\1\67\6\0\1\67\24\0\2\66"+
    "\3\0\3\66\1\67\1\73\1\74\14\0\1\74\6\0"+
    "\1\67\2\0\1\67\6\0\1\67\24\0\1\162\1\163"+
    "\2\0\5\163\1\0\1\163\4\0\2\163\3\0\1\163"+
    "\2\0\1\163\6\0\1\163\2\0\1\163\5\0\2\163"+
    "\24\0\1\164\1\66\1\67\2\0\3\164\1\67\1\73"+
    "\1\74\13\0\1\67\1\74\6\0\1\67\2\0\1\67"+
    "\6\0\1\67\24\0\1\71\1\66\1\67\2\0\3\71"+
    "\1\67\1\73\1\74\13\0\1\67\1\74\6\0\1\67"+
    "\2\0\1\67\6\0\1\67\24\0\2\73\3\0\3\73"+
    "\1\67\1\0\1\74\14\0\1\74\6\0\1\67\2\0"+
    "\1\67\6\0\1\67\24\0\2\165\3\0\3\165\3\0"+
    "\1\166\50\0\1\166\6\0\13\11\1\0\1\11\4\0"+
    "\6\11\1\167\27\11\16\0\13\11\1\0\1\11\4\0"+
    "\2\11\1\170\33\11\16\0\13\11\1\0\1\11\4\0"+
    "\10\11\1\171\25\11\16\0\13\11\1\0\1\11\4\0"+
    "\6\11\1\172\27\11\16\0\13\11\1\0\1\11\4\0"+
    "\3\11\1\173\32\11\16\0\13\11\1\0\1\11\4\0"+
    "\1\174\3\11\1\175\31\11\16\0\13\11\1\0\1\11"+
    "\4\0\11\11\1\176\24\11\16\0\13\11\1\0\1\11"+
    "\4\0\6\11\1\177\27\11\16\0\13\11\1\0\1\11"+
    "\4\0\23\11\1\200\12\11\16\0\13\11\1\0\1\11"+
    "\4\0\15\11\1\201\20\11\16\0\13\11\1\0\1\11"+
    "\4\0\1\202\12\11\1\127\2\11\1\173\17\11\16\0"+
    "\13\11\1\0\1\11\4\0\4\11\1\203\10\11\1\204"+
    "\20\11\16\0\13\11\1\0\1\11\4\0\3\11\1\205"+
    "\32\11\16\0\13\11\1\0\1\11\4\0\2\11\1\173"+
    "\1\206\32\11\16\0\13\11\1\0\1\11\4\0\11\11"+
    "\1\207\24\11\16\0\13\11\1\0\1\11\4\0\1\210"+
    "\35\11\16\0\13\11\1\0\1\11\4\0\1\133\35\11"+
    "\16\0\13\11\1\0\1\11\4\0\11\11\1\211\24\11"+
    "\16\0\13\11\1\0\1\11\4\0\2\11\1\173\33\11"+
    "\16\0\13\11\1\0\1\11\4\0\16\11\1\212\17\11"+
    "\16\0\13\11\1\0\1\11\4\0\3\11\1\213\32\11"+
    "\16\0\13\11\1\0\1\11\4\0\3\11\1\214\32\11"+
    "\16\0\13\11\1\0\1\11\4\0\26\11\1\127\7\11"+
    "\16\0\13\11\1\0\1\11\4\0\7\11\1\215\26\11"+
    "\16\0\13\11\1\0\1\11\4\0\2\11\1\216\1\217"+
    "\32\11\16\0\13\11\1\0\1\11\4\0\23\11\1\220"+
    "\12\11\16\0\13\11\1\0\1\11\4\0\16\11\1\221"+
    "\17\11\16\0\13\11\1\0\1\11\4\0\22\11\1\222"+
    "\13\11\16\0\13\11\1\0\1\11\4\0\7\11\1\117"+
    "\26\11\16\0\13\11\1\0\1\11\4\0\4\11\1\127"+
    "\31\11\16\0\13\11\1\0\1\11\4\0\6\11\1\223"+
    "\27\11\16\0\13\11\1\0\1\11\4\0\11\11\1\224"+
    "\24\11\16\0\13\11\1\0\1\11\4\0\5\11\1\225"+
    "\30\11\16\0\13\11\1\0\1\11\4\0\6\11\1\226"+
    "\6\11\1\227\20\11\16\0\13\11\1\0\1\11\4\0"+
    "\1\11\1\230\34\11\16\0\13\11\1\0\1\11\4\0"+
    "\3\11\1\231\32\11\16\0\13\11\1\0\1\11\4\0"+
    "\7\11\1\232\5\11\1\233\20\11\16\0\13\11\1\0"+
    "\1\11\4\0\15\11\1\234\20\11\16\0\13\11\1\0"+
    "\1\11\4\0\6\11\1\235\27\11\16\0\13\11\1\0"+
    "\1\11\4\0\3\11\1\236\32\11\16\0\13\11\1\0"+
    "\1\11\4\0\16\11\1\237\17\11\16\0\13\11\1\0"+
    "\1\11\4\0\3\11\1\240\32\11\16\0\13\11\1\0"+
    "\1\11\4\0\34\11\1\241\1\11\16\0\13\11\1\0"+
    "\1\11\4\0\4\11\1\242\31\11\16\0\13\11\1\0"+
    "\1\11\4\0\6\11\1\243\27\11\76\0\1\46\1\10"+
    "\15\0\1\156\4\0\3\156\65\0\1\244\4\0\3\244"+
    "\57\0\1\160\72\0\4\64\1\160\1\161\67\64\10\0"+
    "\1\162\1\163\1\67\1\0\5\163\1\0\1\163\4\0"+
    "\2\163\3\0\1\163\1\0\1\67\1\163\6\0\1\163"+
    "\2\0\1\163\5\0\2\163\24\0\2\245\1\67\1\0"+
    "\5\245\1\0\1\245\4\0\2\245\3\0\1\245\1\0"+
    "\1\67\1\245\6\0\1\245\2\0\1\245\5\0\2\245"+
    "\24\0\1\246\1\66\1\67\2\0\3\246\1\67\1\73"+
    "\1\74\13\0\1\67\1\74\6\0\1\67\2\0\1\67"+
    "\6\0\1\67\24\0\2\165\3\0\3\165\1\67\25\0"+
    "\1\67\2\0\1\67\6\0\1\67\24\0\2\165\3\0"+
    "\3\165\63\0\13\11\1\0\1\11\4\0\1\247\35\11"+
    "\16\0\13\11\1\0\1\11\4\0\3\11\1\250\32\11"+
    "\16\0\13\11\1\0\1\11\4\0\1\251\35\11\16\0"+
    "\13\11\1\0\1\11\4\0\7\11\1\252\26\11\16\0"+
    "\13\11\1\0\1\11\4\0\10\11\1\127\25\11\16\0"+
    "\13\11\1\0\1\11\4\0\3\11\1\253\32\11\16\0"+
    "\13\11\1\0\1\11\4\0\15\11\1\254\20\11\16\0"+
    "\13\11\1\0\1\11\4\0\5\11\1\255\30\11\16\0"+
    "\13\11\1\0\1\11\4\0\4\11\1\256\31\11\16\0"+
    "\13\11\1\0\1\11\4\0\10\11\1\133\25\11\16\0"+
    "\13\11\1\0\1\11\4\0\3\11\1\206\32\11\16\0"+
    "\13\11\1\0\1\11\4\0\11\11\1\257\24\11\16\0"+
    "\13\11\1\0\1\11\4\0\6\11\1\260\27\11\16\0"+
    "\13\11\1\0\1\11\4\0\2\11\1\127\33\11\16\0"+
    "\13\11\1\0\1\11\4\0\16\11\1\261\17\11\16\0"+
    "\13\11\1\0\1\11\4\0\5\11\1\262\30\11\16\0"+
    "\13\11\1\0\1\11\4\0\2\11\1\256\1\263\32\11"+
    "\16\0\13\11\1\0\1\11\4\0\2\11\1\204\33\11"+
    "\16\0\13\11\1\0\1\11\4\0\24\11\1\127\11\11"+
    "\16\0\13\11\1\0\1\11\4\0\20\11\1\127\15\11"+
    "\16\0\13\11\1\0\1\11\4\0\10\11\1\264\25\11"+
    "\16\0\13\11\1\0\1\11\4\0\15\11\1\265\20\11"+
    "\16\0\13\11\1\0\1\11\4\0\7\11\1\127\26\11"+
    "\16\0\13\11\1\0\1\11\4\0\3\11\1\266\32\11"+
    "\16\0\13\11\1\0\1\11\4\0\10\11\1\267\25\11"+
    "\16\0\13\11\1\0\1\11\4\0\6\11\1\177\1\270"+
    "\26\11\16\0\13\11\1\0\1\11\4\0\1\11\1\234"+
    "\34\11\16\0\13\11\1\0\1\11\4\0\1\271\35\11"+
    "\16\0\13\11\1\0\1\11\4\0\1\256\35\11\16\0"+
    "\13\11\1\0\1\11\4\0\1\272\35\11\16\0\13\11"+
    "\1\0\1\11\4\0\12\11\1\273\23\11\16\0\13\11"+
    "\1\0\1\11\4\0\3\11\1\274\32\11\16\0\13\11"+
    "\1\0\1\11\4\0\25\11\1\275\10\11\16\0\13\11"+
    "\1\0\1\11\4\0\7\11\1\253\26\11\16\0\13\11"+
    "\1\0\1\11\4\0\6\11\1\127\27\11\16\0\13\11"+
    "\1\0\1\11\4\0\1\276\35\11\16\0\13\11\1\0"+
    "\1\11\4\0\17\11\1\127\16\11\16\0\13\11\1\0"+
    "\1\11\4\0\7\11\1\173\26\11\16\0\13\11\1\0"+
    "\1\11\4\0\7\11\1\277\26\11\16\0\13\11\1\0"+
    "\1\11\4\0\10\11\1\300\25\11\16\0\13\11\1\0"+
    "\1\11\4\0\1\11\1\301\34\11\16\0\13\11\1\0"+
    "\1\11\4\0\10\11\1\302\25\11\16\0\13\11\1\0"+
    "\1\11\4\0\10\11\1\303\25\11\16\0\13\11\1\0"+
    "\1\11\4\0\15\11\1\304\20\11\16\0\13\11\1\0"+
    "\1\11\4\0\4\11\1\247\31\11\20\0\2\305\1\67"+
    "\1\0\5\305\1\0\1\305\4\0\2\305\3\0\1\305"+
    "\1\0\1\67\1\305\6\0\1\305\2\0\1\305\5\0"+
    "\2\305\24\0\1\306\1\66\1\67\2\0\3\306\1\67"+
    "\1\73\1\74\13\0\1\67\1\74\6\0\1\67\2\0"+
    "\1\67\6\0\1\67\22\0\13\11\1\0\1\11\4\0"+
    "\3\11\1\300\32\11\16\0\13\11\1\0\1\11\4\0"+
    "\4\11\1\307\31\11\16\0\13\11\1\0\1\11\4\0"+
    "\12\11\1\127\23\11\16\0\13\11\1\0\1\11\4\0"+
    "\10\11\1\310\25\11\16\0\13\11\1\0\1\11\4\0"+
    "\15\11\1\311\20\11\16\0\13\11\1\0\1\11\4\0"+
    "\5\11\1\312\30\11\16\0\13\11\1\0\1\11\4\0"+
    "\14\11\1\313\21\11\16\0\13\11\1\0\1\11\4\0"+
    "\3\11\1\127\32\11\16\0\13\11\1\0\1\11\4\0"+
    "\2\11\1\314\33\11\16\0\13\11\1\0\1\11\4\0"+
    "\26\11\1\315\7\11\16\0\13\11\1\0\1\11\4\0"+
    "\4\11\1\316\31\11\16\0\13\11\1\0\1\11\4\0"+
    "\14\11\1\127\21\11\16\0\13\11\1\0\1\11\4\0"+
    "\15\11\1\317\20\11\16\0\13\11\1\0\1\11\4\0"+
    "\11\11\1\320\24\11\16\0\13\11\1\0\1\11\4\0"+
    "\25\11\1\173\10\11\16\0\13\11\1\0\1\11\4\0"+
    "\1\321\35\11\16\0\13\11\1\0\1\11\4\0\4\11"+
    "\1\322\31\11\16\0\13\11\1\0\1\11\4\0\10\11"+
    "\1\323\25\11\16\0\13\11\1\0\1\11\4\0\16\11"+
    "\1\324\17\11\16\0\13\11\1\0\1\11\4\0\7\11"+
    "\1\325\26\11\16\0\13\11\1\0\1\11\4\0\1\326"+
    "\35\11\16\0\13\11\1\0\1\11\4\0\10\11\1\327"+
    "\25\11\16\0\13\11\1\0\1\11\4\0\1\101\35\11"+
    "\16\0\13\11\1\0\1\11\4\0\3\11\1\143\32\11"+
    "\16\0\13\11\1\0\1\11\4\0\10\11\1\330\25\11"+
    "\16\0\13\11\1\0\1\11\4\0\7\11\1\236\26\11"+
    "\16\0\13\11\1\0\1\11\4\0\24\11\1\331\11\11"+
    "\16\0\13\11\1\0\1\11\4\0\5\11\1\247\30\11"+
    "\16\0\13\11\1\0\1\11\4\0\11\11\1\332\24\11"+
    "\20\0\2\333\1\67\1\0\5\333\1\0\1\333\4\0"+
    "\2\333\3\0\1\333\1\0\1\67\1\333\6\0\1\333"+
    "\2\0\1\333\5\0\2\333\24\0\1\334\1\66\1\67"+
    "\2\0\3\334\1\67\1\73\1\74\13\0\1\67\1\74"+
    "\6\0\1\67\2\0\1\67\6\0\1\67\22\0\13\11"+
    "\1\0\1\11\4\0\1\335\35\11\16\0\13\11\1\0"+
    "\1\11\4\0\1\316\35\11\16\0\13\11\1\0\1\11"+
    "\4\0\5\11\1\127\30\11\16\0\13\11\1\0\1\11"+
    "\4\0\3\11\1\336\32\11\16\0\13\11\1\0\1\11"+
    "\4\0\4\11\1\337\31\11\16\0\13\11\1\0\1\11"+
    "\4\0\15\11\1\340\20\11\16\0\13\11\1\0\1\11"+
    "\4\0\11\11\1\127\24\11\16\0\13\11\1\0\1\11"+
    "\4\0\11\11\1\341\24\11\16\0\13\11\1\0\1\11"+
    "\4\0\17\11\1\204\16\11\16\0\13\11\1\0\1\11"+
    "\4\0\11\11\1\342\24\11\16\0\13\11\1\0\1\11"+
    "\4\0\22\11\1\343\13\11\16\0\13\11\1\0\1\11"+
    "\4\0\20\11\1\344\15\11\16\0\13\11\1\0\1\11"+
    "\4\0\7\11\1\256\26\11\16\0\13\11\1\0\1\11"+
    "\4\0\7\11\1\345\26\11\16\0\13\11\1\0\1\11"+
    "\4\0\24\11\1\173\11\11\16\0\13\11\1\0\1\11"+
    "\4\0\5\11\1\346\30\11\16\0\13\11\1\0\1\11"+
    "\4\0\1\347\35\11\16\0\13\11\1\0\1\11\4\0"+
    "\10\11\1\350\25\11\16\0\13\11\1\0\1\11\4\0"+
    "\24\11\1\300\11\11\20\0\2\351\1\67\1\0\5\351"+
    "\1\0\1\351\4\0\2\351\3\0\1\351\1\0\1\67"+
    "\1\351\6\0\1\351\2\0\1\351\5\0\2\351\24\0"+
    "\1\352\1\66\1\67\2\0\3\352\1\67\1\73\1\74"+
    "\13\0\1\67\1\74\6\0\1\67\2\0\1\67\6\0"+
    "\1\67\22\0\13\11\1\0\1\11\4\0\5\11\1\256"+
    "\30\11\16\0\13\11\1\0\1\11\4\0\22\11\1\353"+
    "\13\11\16\0\13\11\1\0\1\11\4\0\6\11\1\354"+
    "\27\11\16\0\13\11\1\0\1\11\4\0\10\11\1\355"+
    "\25\11\16\0\13\11\1\0\1\11\4\0\16\11\1\173"+
    "\17\11\16\0\13\11\1\0\1\11\4\0\5\11\1\356"+
    "\30\11\16\0\13\11\1\0\1\11\4\0\1\357\35\11"+
    "\16\0\13\11\1\0\1\11\4\0\10\11\1\360\25\11"+
    "\16\0\13\11\1\0\1\11\4\0\13\11\1\127\22\11"+
    "\16\0\13\11\1\0\1\11\4\0\3\11\1\361\32\11"+
    "\16\0\13\11\1\0\1\11\4\0\11\11\1\300\24\11"+
    "\16\0\13\11\1\0\1\11\4\0\4\11\1\300\31\11"+
    "\20\0\2\362\1\67\1\0\5\362\1\0\1\362\4\0"+
    "\2\362\3\0\1\362\1\0\1\67\1\362\6\0\1\362"+
    "\2\0\1\362\5\0\2\362\24\0\1\363\1\66\1\67"+
    "\2\0\3\363\1\67\1\73\1\74\13\0\1\67\1\74"+
    "\6\0\1\67\2\0\1\67\6\0\1\67\22\0\13\11"+
    "\1\0\1\11\4\0\23\11\1\127\12\11\16\0\13\11"+
    "\1\0\1\11\4\0\11\11\1\364\24\11\16\0\13\11"+
    "\1\0\1\11\4\0\11\11\1\256\24\11\16\0\13\11"+
    "\1\0\1\11\4\0\10\11\1\365\25\11\16\0\13\11"+
    "\1\0\1\11\4\0\5\11\1\173\30\11\16\0\13\11"+
    "\1\0\1\11\4\0\11\11\1\366\24\11\16\0\13\11"+
    "\1\0\1\11\4\0\10\11\1\233\25\11\20\0\2\367"+
    "\1\67\1\0\5\367\1\0\1\367\4\0\2\367\3\0"+
    "\1\367\1\0\1\67\1\367\6\0\1\367\2\0\1\367"+
    "\5\0\2\367\24\0\1\370\1\66\1\67\2\0\3\370"+
    "\1\67\1\73\1\74\13\0\1\67\1\74\6\0\1\67"+
    "\2\0\1\67\6\0\1\67\22\0\13\11\1\0\1\11"+
    "\4\0\15\11\1\371\20\11\16\0\13\11\1\0\1\11"+
    "\4\0\6\11\1\372\27\11\16\0\13\11\1\0\1\11"+
    "\4\0\3\11\1\204\32\11\20\0\2\373\1\67\1\0"+
    "\5\373\1\0\1\373\4\0\2\373\3\0\1\373\1\0"+
    "\1\67\1\373\6\0\1\373\2\0\1\373\5\0\2\373"+
    "\24\0\1\374\1\66\1\67\2\0\3\374\1\67\1\73"+
    "\1\74\13\0\1\67\1\74\6\0\1\67\2\0\1\67"+
    "\6\0\1\67\22\0\13\11\1\0\1\11\4\0\27\11"+
    "\1\361\6\11\16\0\13\11\1\0\1\11\4\0\22\11"+
    "\1\127\13\11\20\0\2\375\1\67\1\0\5\375\1\0"+
    "\1\375\4\0\2\375\3\0\1\375\1\0\1\67\1\375"+
    "\6\0\1\375\2\0\1\375\5\0\2\375\24\0\1\376"+
    "\1\66\1\67\2\0\3\376\1\67\1\73\1\74\13\0"+
    "\1\67\1\74\6\0\1\67\2\0\1\67\6\0\1\67"+
    "\24\0\2\377\1\67\1\0\5\377\1\0\1\377\4\0"+
    "\2\377\3\0\1\377\1\0\1\67\1\377\6\0\1\377"+
    "\2\0\1\377\5\0\2\377\24\0\1\u0100\1\66\1\67"+
    "\2\0\3\u0100\1\67\1\73\1\74\13\0\1\67\1\74"+
    "\6\0\1\67\2\0\1\67\6\0\1\67\24\0\2\u0101"+
    "\1\67\1\0\5\u0101\1\0\1\u0101\4\0\2\u0101\3\0"+
    "\1\u0101\1\0\1\67\1\u0101\6\0\1\u0101\2\0\1\u0101"+
    "\5\0\2\u0101\24\0\1\u0102\1\66\1\67\2\0\3\u0102"+
    "\1\67\1\73\1\74\13\0\1\67\1\74\6\0\1\67"+
    "\2\0\1\67\6\0\1\67\24\0\2\u0103\1\67\1\0"+
    "\5\u0103\1\0\1\u0103\4\0\2\u0103\3\0\1\u0103\1\0"+
    "\1\67\1\u0103\6\0\1\u0103\2\0\1\u0103\5\0\2\u0103"+
    "\24\0\1\u0104\1\66\1\67\2\0\3\u0104\1\67\1\73"+
    "\1\74\13\0\1\67\1\74\6\0\1\67\2\0\1\67"+
    "\6\0\1\67\24\0\2\u0105\1\67\1\0\5\u0105\1\0"+
    "\1\u0105\4\0\2\u0105\3\0\1\u0105\1\0\1\67\1\u0105"+
    "\6\0\1\u0105\2\0\1\u0105\5\0\2\u0105\24\0\1\u0106"+
    "\1\66\1\67\2\0\3\u0106\1\67\1\73\1\74\13\0"+
    "\1\67\1\74\6\0\1\67\2\0\1\67\6\0\1\67"+
    "\24\0\2\u0107\1\67\1\0\5\u0107\1\0\1\u0107\4\0"+
    "\2\u0107\3\0\1\u0107\1\0\1\67\1\u0107\6\0\1\u0107"+
    "\2\0\1\u0107\5\0\2\u0107\24\0\1\u0108\1\66\1\67"+
    "\2\0\3\u0108\1\67\1\73\1\74\13\0\1\67\1\74"+
    "\6\0\1\67\2\0\1\67\6\0\1\67\24\0\2\u0109"+
    "\1\67\1\0\5\u0109\1\0\1\u0109\4\0\2\u0109\3\0"+
    "\1\u0109\1\0\1\67\1\u0109\6\0\1\u0109\2\0\1\u0109"+
    "\5\0\2\u0109\24\0\1\u010a\1\66\1\67\2\0\3\u010a"+
    "\1\67\1\73\1\74\13\0\1\67\1\74\6\0\1\67"+
    "\2\0\1\67\6\0\1\67\24\0\2\u010b\1\67\1\0"+
    "\5\u010b\1\0\1\u010b\4\0\2\u010b\3\0\1\u010b\1\0"+
    "\1\67\1\u010b\6\0\1\u010b\2\0\1\u010b\5\0\2\u010b"+
    "\24\0\1\u010c\1\66\1\67\2\0\3\u010c\1\67\1\73"+
    "\1\74\13\0\1\67\1\74\6\0\1\67\2\0\1\67"+
    "\6\0\1\67\26\0\1\67\23\0\1\67\46\0\1\u010d"+
    "\1\66\1\67\2\0\3\u010d\1\67\1\73\1\74\13\0"+
    "\1\67\1\74\6\0\1\67\2\0\1\67\6\0\1\67"+
    "\24\0\1\u010e\1\66\1\67\2\0\3\u010e\1\67\1\73"+
    "\1\74\13\0\1\67\1\74\6\0\1\67\2\0\1\67"+
    "\6\0\1\67\24\0\1\u010f\1\66\1\67\2\0\3\u010f"+
    "\1\67\1\73\1\74\13\0\1\67\1\74\6\0\1\67"+
    "\2\0\1\67\6\0\1\67\24\0\1\u0110\1\66\1\67"+
    "\2\0\3\u0110\1\67\1\73\1\74\13\0\1\67\1\74"+
    "\6\0\1\67\2\0\1\67\6\0\1\67\24\0\2\66"+
    "\1\67\2\0\3\66\1\67\1\73\1\74\13\0\1\67"+
    "\1\74\6\0\1\67\2\0\1\67\6\0\1\67\14\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[15860];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\1\11\12\1\2\11\25\1\1\11\7\1\2\11"+
    "\4\1\1\0\2\1\1\11\1\0\3\1\1\0\57\1"+
    "\1\11\3\1\1\11\1\0\4\1\1\0\55\1\1\11"+
    "\130\1\1\0\1\1\1\0\1\1\1\0\1\1\1\0"+
    "\1\1\1\0\1\1\1\0\1\1\1\0\1\1\1\0"+
    "\5\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[272];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /* user code: */
    /**
     * Create an empty lexer, yyrset will be called later to reset and assign
     * the reader
     */
    public JavaLexer() {
        super();
    }

    private Token token(TokenType type) {
        return new Token(type, yychar, yylength());
    }

    // These will be used to store Token Start positions and length for Complex 
    // Tokens that need deifferent Lexer States, like STRING
    int tokenStart;
    int tokenLength;

    public static String[] LANGS = new String[] { "java" };



  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public JavaLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public JavaLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 1798) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 11: 
          { return token(TokenType.KEYWORD);
          }
        case 14: break;
        case 5: 
          { yybegin(STRING); 
                                    tokenStart = yychar; 
                                    tokenLength = 1;
          }
        case 15: break;
        case 12: 
          { tokenLength += 2;
          }
        case 16: break;
        case 3: 
          { return token(TokenType.IDENT);
          }
        case 17: break;
        case 6: 
          { yybegin(CHARLITERAL); 
                                    tokenStart = yychar; 
                                    tokenLength = 1;
          }
        case 18: break;
        case 9: 
          { yybegin(YYINITIAL); 
                                     // length also includes the trailing quote
                                     return new Token(TokenType.STRING, tokenStart, tokenLength + 1);
          }
        case 19: break;
        case 10: 
          { return token(TokenType.COMMENT);
          }
        case 20: break;
        case 2: 
          { return token(TokenType.OPER);
          }
        case 21: break;
        case 13: 
          { return token(TokenType.TYPE);
          }
        case 22: break;
        case 4: 
          { return token(TokenType.NUMBER);
          }
        case 23: break;
        case 8: 
          { yybegin(YYINITIAL);
          }
        case 24: break;
        case 1: 
          { 
          }
        case 25: break;
        case 7: 
          { tokenLength += yylength();
          }
        case 26: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
              {
                return null;
              }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
